---
   - name: Create Gunicorn Socket file
     template: src=gunicorn.socket.j2 dest=/etc/systemd/system/gunicorn.socket

   - name: Create Gunicorn Service file
     template: src=gunicorn.service.j2 dest=/etc/systemd/system/gunicorn.service

   - name: Start Gunicorn.socket
     shell: "/bin/systemctl start gunicorn.socket"

   - name: Enable Gunicorn.socket
     shell: "/bin/systemctl enable gunicorn.socket"
